# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish package to Github Packages

on:
  push:
    branches:
      - create-docs-site
  workflow_dispatch:
    inputs:
      version:
        description: 'Package Version Number'
        required: true
        default: "0.0.1"
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - run: yarn test

  publish-package:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: 'https://npm.pkg.github.com'
          always-auth: true

      - name: Install Json CLI
        run: "npm install json -g"

      - name: Change package.json version number
        run: "json -I -f package.json -e \"this.version=\'$VERSION\'\""
        env:
          VERSION: 0.0.3

      - name: Install Dependencies
        run: yarn

      - name: Build Distribution
        run: yarn build

      - name: Publish
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
